

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: url_shortener
      JWT_SECRET: rajan_super_secret_key
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: url_shortener
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
